name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Make sure all images are webp
        env:
          CI: true
        run: |
          npm run images-to-webp

      - name: Serve app
        env:
          PORT: 3000
        run: |

          npm run start &
          sleep 1
          curl --fail --retry-connrefused --retry 3 localhost:3000
          curl --fail http://localhost:3000/bilder
          curl --fail http://localhost:3000/kontakt
          curl --fail http://localhost:3000/bilder/frank-zappa
